### ISSUE TITLE
Opportunity to change file extension without visiting settings

### ISSUE THREAD

**Issue by brettz9** [jcouyang/glist#13]
你好！ Great tool!

I'd like to request the ability, when adding a title in the search dialog, to also add a file extension which would allow an override of the default extension from settings. I don't know if you could add a separate text box, or just automatically search for something like `\..*?$`. Thanks!

**Comment by jcouyang** [comment]
Cool, That's really good idea, I'll let you know if I got time implement it :) thanks

but for now, alternatively you can create a whatever file, and it will actually create a gist folder for you, you can see it will display on the tree directory, then you can create any file there and sync.

**Comment by mhakfoort** [comment]
Seconded, this would be very useful!

**Comment by jcouyang** [comment]
closed by https://github.com/jcouyang/glist/releases/tag/v2.2.0
