### ISSUE TITLE
Seems unable to change default gist dir

### ISSUE THREAD

**Issue by ebalsumgo** [jcouyang/glist#17]
I keep trying to set the gist dir to something other than defualt, but I cannot. Any time I change it and go to open a gist i just sit on Opening gist and nothing happens. If i remove my custom path (which does exist) it opens up the gist just fine.

**Comment by jcouyang** [comment]
yeah, I already mention this in README https://github.com/jcouyang/glist#gist-directory
sure, I've tried using `~` in path, but Directory api from atom seems only accept absolute path
