### ISSUE TITLE
Token is not masked and stored in main config

### ISSUE THREAD

**Issue by blimmer** [jcouyang/glist#19]
Just installed this and, though it works, my token is stored in `~/.atom/config.cson`, not in the supposed default path. It's also not masked in the settings page.

```bash
› atom --version
1.4.3

glist version 2.2.0
```

**Comment by jcouyang** [comment]
have you tried to restart Atom?

**Comment by blimmer** [comment]
Ah, yes, a restart does seem to fix it. You might note on the settings page/docs that a restart is required.

**Comment by aronbeal** [comment]
I ran into this as well.  I'd also note that entering a github personal access api token results in invalid credentials until a restart is accomplished.
