### ISSUE TITLE
[FEATURE] Glist is awesome, let's add a description to our gists

### ISSUE THREAD

**Issue by exocode** [jcouyang/glist#30]
In order to fill out the description field which gists provide, I need a form field.
It would be cool when there would be anywhere a text field to add description to our gists.

**Comment by jcouyang** [comment]
glist supported adding description already, just `c-x c-s` it will pop up a form

![](https://www.evernote.com/l/ABc2hooxaBZNrKr5V3IRWHd-6AbcmXRR0agB/image.png)

**Comment by exocode** [comment]
Thank you I did not recognized it
