### ISSUE TITLE
no username or token field in settings / fatal: could not read...

### ISSUE THREAD

**Issue by tessus** [jcouyang/glist#5]
If I try to save an updated GIST with ctrl-x ctrl-s, I get the following error:

![error](https://cloud.githubusercontent.com/assets/223439/4980912/738cc140-6904-11e4-8ad6-98352bf299f1.png)

According to the documentation, I'm supposed to enter my username and token in the settings for glist, but there are no fields to enter that information:

![settings](https://cloud.githubusercontent.com/assets/223439/4980936/9cf2e960-6904-11e4-9d85-80823c5b7858.png)

Please advise.

**Comment by tessus** [comment]
Any news on this? It's been 7 months. :-)

**Comment by jcouyang** [comment]
I rewrote the whole package now it's version 2.0
please do upgrade and really appreciate any feedback
