### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by iamioannis** [jcouyang/glist#8]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:54:11)
GlistView.showFormAs (/Users/ioannis/.atom/packages/glist/lib/glist-view.coffee:227:9)
```

**Comment by iamioannis** [comment]
I tried to change the .workplace property to .atom-workplace as Atom suggested but Glist didn't really like it. I hope that helps

**Comment by jcouyang** [comment]
I rewrote the whole package now it's version 2.0
please do upgrade and really appreciate any feedback

**Comment by iamioannis** [comment]
Thanks for your dedication. Will give a retest.
